services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dine-reservation-service:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ../.env
    command: sh -c "npm run migrate:deploy && npm start"

  db:
    image: postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
